/* main.c generated by valac, the Vala compiler
 * generated from main.vala, do not modify */

/* 
 * gtkpdf
 * GTK+ PDF reader
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <poppler.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <stdio.h>
#include <gdk-pixbuf/gdk-pixdata.h>


#define TYPE_PDF_READER (pdf_reader_get_type ())
#define PDF_READER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PDF_READER, PdfReader))
#define PDF_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PDF_READER, PdfReaderClass))
#define IS_PDF_READER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PDF_READER))
#define IS_PDF_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PDF_READER))
#define PDF_READER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PDF_READER, PdfReaderClass))

typedef struct _PdfReader PdfReader;
typedef struct _PdfReaderClass PdfReaderClass;
typedef struct _PdfReaderPrivate PdfReaderPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _PdfReader {
	GObject parent_instance;
	PdfReaderPrivate * priv;
	GtkImage* image;
	GtkStatusbar* statusbar;
};

struct _PdfReaderClass {
	GObjectClass parent_class;
};

struct _PdfReaderPrivate {
	PopplerDocument* pdf;
	char* document;
	gint index;
	gint ptotal;
	double ratio;
	GtkWindow* _window;
};


static gpointer pdf_reader_parent_class = NULL;

GType pdf_reader_get_type (void);
#define PDF_READER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PDF_READER, PdfReaderPrivate))
enum  {
	PDF_READER_DUMMY_PROPERTY,
	PDF_READER_WINDOW
};
void pdf_reader_set_window (PdfReader* self, GtkWindow* value);
GtkWindow* pdf_reader_get_window (PdfReader* self);
static void _gtk_main_quit_gtk_object_destroy (GtkObject* _sender, gpointer self);
PdfReader* pdf_reader_new (void);
PdfReader* pdf_reader_construct (GType object_type);
void pdf_reader_on_menuabout_activate (GtkWidget* source, PdfReader* self);
void pdf_reader_reader (PdfReader* self, const char* document);
void pdf_reader_on_buttonzoomin_clicked (GtkWidget* source, PdfReader* self);
void pdf_reader_on_buttonzoomout_clicked (GtkWidget* source, PdfReader* self);
void pdf_reader_on_buttonpagefwd_clicked (GtkWidget* source, PdfReader* self);
void pdf_reader_on_buttonpageback_clicked (GtkWidget* source, PdfReader* self);
void pdf_reader_on_menuopen_activate (GtkWidget* source, PdfReader* self);
static void pdf_reader_finalize (GObject* obj);
static void pdf_reader_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void pdf_reader_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
void _main (char** args, int args_length1);



static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


#line 7581 "gtk+-2.0.vapi"
static void _gtk_main_quit_gtk_object_destroy (GtkObject* _sender, gpointer self) {
#line 92 "main.c"
	gtk_main_quit ();
}


#line 25 "main.vala"
PdfReader* pdf_reader_construct (GType object_type) {
#line 99 "main.c"
	GError * _inner_error_;
	PdfReader * self;
	_inner_error_ = NULL;
#line 25 "main.vala"
	self = (PdfReader*) g_object_new (object_type, NULL);
#line 105 "main.c"
	{
		GtkBuilder* builder;
		GObject* _tmp0_;
		GtkImage* _tmp2_;
		GObject* _tmp1_;
		GtkStatusbar* _tmp4_;
		GObject* _tmp3_;
#line 28 "main.vala"
		builder = gtk_builder_new ();
#line 30 "main.vala"
		gtk_builder_add_from_file (builder, "main.ui", &_inner_error_);
#line 117 "main.c"
		if (_inner_error_ != NULL) {
			_g_object_unref0 (builder);
			goto __catch0_g_error;
		}
#line 32 "main.vala"
		pdf_reader_set_window (self, (_tmp0_ = gtk_builder_get_object (builder, "window"), GTK_IS_WINDOW (_tmp0_) ? ((GtkWindow*) _tmp0_) : NULL));
#line 33 "main.vala"
		self->image = (_tmp2_ = _g_object_ref0 ((_tmp1_ = gtk_builder_get_object (builder, "image1"), GTK_IS_IMAGE (_tmp1_) ? ((GtkImage*) _tmp1_) : NULL)), _g_object_unref0 (self->image), _tmp2_);
#line 34 "main.vala"
		self->statusbar = (_tmp4_ = _g_object_ref0 ((_tmp3_ = gtk_builder_get_object (builder, "statusbar1"), GTK_IS_STATUSBAR (_tmp3_) ? ((GtkStatusbar*) _tmp3_) : NULL)), _g_object_unref0 (self->statusbar), _tmp4_);
#line 36 "main.vala"
		g_signal_connect ((GtkObject*) self->priv->_window, "destroy", (GCallback) _gtk_main_quit_gtk_object_destroy, NULL);
#line 37 "main.vala"
		gtk_builder_connect_signals (builder, self);
#line 132 "main.c"
		_g_object_unref0 (builder);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
#line 41 "main.vala"
			fprintf (stderr, "Could not load UI: %s", e->message);
#line 144 "main.c"
			_g_error_free0 (e);
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	return self;
}


#line 25 "main.vala"
PdfReader* pdf_reader_new (void) {
#line 25 "main.vala"
	return pdf_reader_construct (TYPE_PDF_READER);
#line 162 "main.c"
}


#line 46 "main.vala"
void pdf_reader_on_menuabout_activate (GtkWidget* source, PdfReader* self) {
#line 168 "main.c"
	GtkMessageDialog* dialog;
#line 46 "main.vala"
	g_return_if_fail (self != NULL);
#line 46 "main.vala"
	g_return_if_fail (source != NULL);
#line 48 "main.vala"
	dialog = g_object_ref_sink ((GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_DESTROY_WITH_PARENT | GTK_DIALOG_MODAL, GTK_MESSAGE_INFO, GTK_BUTTONS_CLOSE, "gtkpdf\nGTK+ PDF reader\n\nCopyright (c) 2010, Paolo Radice. All rights reserved."));
#line 54 "main.vala"
	gtk_window_set_title ((GtkWindow*) dialog, "GTK+ PDF reader");
#line 55 "main.vala"
	gtk_dialog_run ((GtkDialog*) dialog);
#line 56 "main.vala"
	gtk_object_destroy ((GtkObject*) dialog);
#line 182 "main.c"
	_g_object_unref0 (dialog);
}


#line 60 "main.vala"
void pdf_reader_on_buttonzoomin_clicked (GtkWidget* source, PdfReader* self) {
#line 60 "main.vala"
	g_return_if_fail (self != NULL);
#line 60 "main.vala"
	g_return_if_fail (source != NULL);
#line 62 "main.vala"
	self->priv->ratio = self->priv->ratio + 0.5;
#line 63 "main.vala"
	pdf_reader_reader (self, self->priv->document);
#line 197 "main.c"
}


#line 67 "main.vala"
void pdf_reader_on_buttonzoomout_clicked (GtkWidget* source, PdfReader* self) {
#line 67 "main.vala"
	g_return_if_fail (self != NULL);
#line 67 "main.vala"
	g_return_if_fail (source != NULL);
#line 70 "main.vala"
	if (self->priv->ratio > 0.5) {
#line 72 "main.vala"
		self->priv->ratio = self->priv->ratio - 0.5;
#line 73 "main.vala"
		pdf_reader_reader (self, self->priv->document);
#line 213 "main.c"
	}
}


#line 78 "main.vala"
void pdf_reader_on_buttonpagefwd_clicked (GtkWidget* source, PdfReader* self) {
#line 78 "main.vala"
	g_return_if_fail (self != NULL);
#line 78 "main.vala"
	g_return_if_fail (source != NULL);
#line 80 "main.vala"
	if ((self->priv->index + 1) < self->priv->ptotal) {
#line 81 "main.vala"
		self->priv->index++;
#line 228 "main.c"
	} else {
#line 83 "main.vala"
		if ((self->priv->index + 1) == self->priv->ptotal) {
#line 84 "main.vala"
			self->priv->index = 0;
#line 234 "main.c"
		} else {
#line 86 "main.vala"
			self->priv->index--;
#line 238 "main.c"
		}
	}
#line 89 "main.vala"
	pdf_reader_reader (self, self->priv->document);
#line 243 "main.c"
}


#line 93 "main.vala"
void pdf_reader_on_buttonpageback_clicked (GtkWidget* source, PdfReader* self) {
#line 93 "main.vala"
	g_return_if_fail (self != NULL);
#line 93 "main.vala"
	g_return_if_fail (source != NULL);
#line 95 "main.vala"
	if (self->priv->index > 0) {
#line 96 "main.vala"
		self->priv->index--;
#line 257 "main.c"
	} else {
#line 98 "main.vala"
		self->priv->index = self->priv->ptotal - 1;
#line 261 "main.c"
	}
#line 100 "main.vala"
	pdf_reader_reader (self, self->priv->document);
#line 265 "main.c"
}


#line 104 "main.vala"
void pdf_reader_on_menuopen_activate (GtkWidget* source, PdfReader* self) {
#line 271 "main.c"
	GtkFileChooserDialog* dialog;
	GtkFileFilter* filter;
#line 104 "main.vala"
	g_return_if_fail (self != NULL);
#line 104 "main.vala"
	g_return_if_fail (source != NULL);
#line 106 "main.vala"
	dialog = g_object_ref_sink ((GtkFileChooserDialog*) gtk_file_chooser_dialog_new ("GTK+ PDF reader", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, GTK_STOCK_OPEN, GTK_RESPONSE_ACCEPT, NULL, NULL));
#line 116 "main.vala"
	filter = g_object_ref_sink (gtk_file_filter_new ());
#line 118 "main.vala"
	gtk_file_filter_set_name (filter, "PDF Documents");
#line 119 "main.vala"
	gtk_file_filter_add_pattern (filter, "*.pdf");
#line 120 "main.vala"
	gtk_file_chooser_add_filter ((GtkFileChooser*) dialog, filter);
#line 121 "main.vala"
	gtk_file_chooser_set_filter ((GtkFileChooser*) dialog, filter);
#line 122 "main.vala"
	gtk_file_chooser_set_select_multiple ((GtkFileChooser*) dialog, FALSE);
#line 124 "main.vala"
	if (gtk_dialog_run ((GtkDialog*) dialog) == GTK_RESPONSE_ACCEPT) {
#line 294 "main.c"
		char* _tmp0_;
#line 126 "main.vala"
		self->priv->document = (_tmp0_ = gtk_file_chooser_get_filename ((GtkFileChooser*) dialog), _g_free0 (self->priv->document), _tmp0_);
#line 127 "main.vala"
		self->priv->index = 0;
#line 128 "main.vala"
		pdf_reader_reader (self, self->priv->document);
#line 302 "main.c"
	}
#line 131 "main.vala"
	gtk_object_destroy ((GtkObject*) dialog);
#line 306 "main.c"
	_g_object_unref0 (dialog);
	_g_object_unref0 (filter);
}


#line 134 "main.vala"
void pdf_reader_reader (PdfReader* self, const char* document) {
#line 314 "main.c"
	GError * _inner_error_;
	char* msg;
	double page_width = 0.0;
	double page_height = 0.0;
	gint twidth = 0;
	gint theight = 0;
#line 134 "main.vala"
	g_return_if_fail (self != NULL);
#line 134 "main.vala"
	g_return_if_fail (document != NULL);
#line 325 "main.c"
	_inner_error_ = NULL;
	msg = NULL;
	{
		char* _tmp0_;
		char* _tmp1_;
		PopplerDocument* _tmp2_;
		PopplerDocument* _tmp3_;
		PopplerDocument* _tmp4_;
		char* _tmp9_;
		char* _tmp8_;
		char* _tmp7_;
		char* _tmp6_;
		char* _tmp5_ = NULL;
		PopplerPage* page;
		gint pnumber;
		char* _tmp14_;
		char* _tmp13_;
		char* _tmp12_;
		char* _tmp11_;
		char* _tmp10_;
		GdkPixbuf* pixbuf;
#line 142 "main.vala"
		_tmp0_ = g_filename_to_uri (document, NULL, &_inner_error_);
#line 349 "main.c"
		if (_inner_error_ != NULL) {
			goto __catch1_g_error;
		}
#line 142 "main.vala"
		_tmp3_ = (_tmp2_ = poppler_document_new_from_file (_tmp1_ = _tmp0_, "", &_inner_error_), _g_free0 (_tmp1_), _tmp2_);
#line 355 "main.c"
		if (_inner_error_ != NULL) {
			goto __catch1_g_error;
		}
#line 142 "main.vala"
		self->priv->pdf = (_tmp4_ = _tmp3_, _g_object_unref0 (self->priv->pdf), _tmp4_);
#line 144 "main.vala"
		gtk_window_set_title (self->priv->_window, _tmp9_ = g_strconcat (_tmp8_ = g_strconcat (_tmp7_ = g_strconcat (_tmp6_ = (g_object_get (self->priv->pdf, "title", &_tmp5_, NULL), _tmp5_), " (", NULL), document, NULL), ")", NULL));
#line 363 "main.c"
		_g_free0 (_tmp9_);
		_g_free0 (_tmp8_);
		_g_free0 (_tmp7_);
		_g_free0 (_tmp6_);
#line 146 "main.vala"
		self->priv->ptotal = poppler_document_get_n_pages (self->priv->pdf);
#line 147 "main.vala"
		page = _g_object_ref0 (poppler_document_get_page (self->priv->pdf, self->priv->index));
#line 149 "main.vala"
		pnumber = self->priv->index + 1;
#line 151 "main.vala"
		msg = (_tmp14_ = g_strconcat (_tmp12_ = g_strconcat (_tmp11_ = g_strconcat ("Page ", _tmp10_ = g_strdup_printf ("%i", pnumber), NULL), " of ", NULL), _tmp13_ = g_strdup_printf ("%i", self->priv->ptotal), NULL), _g_free0 (msg), _tmp14_);
#line 376 "main.c"
		_g_free0 (_tmp13_);
		_g_free0 (_tmp12_);
		_g_free0 (_tmp11_);
		_g_free0 (_tmp10_);
#line 153 "main.vala"
		poppler_page_get_size (page, &page_width, &page_height);
#line 154 "main.vala"
		twidth = (gint) (page_width * self->priv->ratio);
#line 155 "main.vala"
		theight = (gint) (page_height * self->priv->ratio);
#line 157 "main.vala"
		pixbuf = gdk_pixbuf_new (GDK_COLORSPACE_RGB, FALSE, 8, twidth, theight);
#line 159 "main.vala"
		poppler_page_render_to_pixbuf (page, 0, 0, twidth, theight, self->priv->ratio, 0, pixbuf);
#line 161 "main.vala"
		gtk_image_set_from_pixbuf (self->image, pixbuf);
#line 393 "main.c"
		_g_object_unref0 (page);
		_g_object_unref0 (pixbuf);
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			char* _tmp15_;
#line 165 "main.vala"
			msg = (_tmp15_ = g_strconcat ("Error: ", e->message, NULL), _g_free0 (msg), _tmp15_);
#line 407 "main.c"
			_g_error_free0 (e);
		}
	}
	__finally1:
	if (_inner_error_ != NULL) {
		_g_free0 (msg);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
#line 169 "main.vala"
	gtk_statusbar_push (self->statusbar, (guint) 1, msg);
#line 420 "main.c"
	_g_free0 (msg);
}


GtkWindow* pdf_reader_get_window (PdfReader* self) {
	GtkWindow* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_window;
#line 19 "main.vala"
	return result;
#line 431 "main.c"
}


void pdf_reader_set_window (PdfReader* self, GtkWindow* value) {
	GtkWindow* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_window = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_window), _tmp0_);
	g_object_notify ((GObject *) self, "window");
}


static void pdf_reader_class_init (PdfReaderClass * klass) {
	pdf_reader_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PdfReaderPrivate));
	G_OBJECT_CLASS (klass)->get_property = pdf_reader_get_property;
	G_OBJECT_CLASS (klass)->set_property = pdf_reader_set_property;
	G_OBJECT_CLASS (klass)->finalize = pdf_reader_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), PDF_READER_WINDOW, g_param_spec_object ("window", "window", "window", GTK_TYPE_WINDOW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void pdf_reader_instance_init (PdfReader * self) {
	self->priv = PDF_READER_GET_PRIVATE (self);
	self->priv->ratio = 1.0;
}


static void pdf_reader_finalize (GObject* obj) {
	PdfReader * self;
	self = PDF_READER (obj);
	_g_object_unref0 (self->priv->pdf);
	_g_free0 (self->priv->document);
	_g_object_unref0 (self->priv->_window);
	_g_object_unref0 (self->image);
	_g_object_unref0 (self->statusbar);
	G_OBJECT_CLASS (pdf_reader_parent_class)->finalize (obj);
}


GType pdf_reader_get_type (void) {
	static GType pdf_reader_type_id = 0;
	if (pdf_reader_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (PdfReaderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) pdf_reader_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PdfReader), 0, (GInstanceInitFunc) pdf_reader_instance_init, NULL };
		pdf_reader_type_id = g_type_register_static (G_TYPE_OBJECT, "PdfReader", &g_define_type_info, 0);
	}
	return pdf_reader_type_id;
}


static void pdf_reader_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	PdfReader * self;
	self = PDF_READER (object);
	switch (property_id) {
		case PDF_READER_WINDOW:
		g_value_set_object (value, pdf_reader_get_window (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void pdf_reader_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	PdfReader * self;
	self = PDF_READER (object);
	switch (property_id) {
		case PDF_READER_WINDOW:
		pdf_reader_set_window (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


#line 174 "main.vala"
void _main (char** args, int args_length1) {
#line 511 "main.c"
	PdfReader* app;
#line 176 "main.vala"
	gtk_init (&args_length1, &args);
#line 178 "main.vala"
	app = pdf_reader_new ();
#line 179 "main.vala"
	gtk_widget_show_all ((GtkWidget*) pdf_reader_get_window (app));
#line 181 "main.vala"
	gtk_main ();
#line 521 "main.c"
	_g_object_unref0 (app);
}


#line 174 "main.vala"
int main (int argc, char ** argv) {
#line 174 "main.vala"
	g_type_init ();
#line 174 "main.vala"
	_main (argv, argc);
#line 174 "main.vala"
	return 0;
#line 534 "main.c"
}




